# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-27 19:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('software', ckeditor.fields.RichTextField()),
                ('electronic', ckeditor.fields.RichTextField()),
                ('mechanic', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='RoboticsPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RoboticsSponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_success', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='roboticssponsors',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.Season'),
        ),
        migrations.AddField(
            model_name='roboticspress',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.Season'),
        ),
        migrations.AddField(
            model_name='robot',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.Season'),
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robotics.Season'),
        ),
    ]
