# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-27 20:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='electronic',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='robot',
            name='mechanic',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='robot',
            name='software',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='roboticspress',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='roboticssponsors',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
