# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='meeting',
            field=models.BooleanField(default=False, verbose_name='Is this company called?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Is meeting successfull ?'),
        ),
    ]
