# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_auto_20160726_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
